apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: caps-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: caps-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        #args:
        #- --enable-leader-election
        env:
          - name: SCVMM_EXECHOST
            value: stxlr01.europe.stater.corp
          - name: SCVMM_HOST
            value: stvmm.europe.stater.corp
          - name: SCVMM_USERNAME
            valueFrom:
              secretKeyRef:
                name: scvmm-credentials
                key: username
          - name: SCVMM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: scvmm-credentials
                key: password
        image: willemmon/cluster-api-provider-scvmm:WIP-7
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
