# permissions for end users to edit scvmmnamepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scvmmnamepool-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-scvmm-new
    app.kubernetes.io/part-of: cluster-api-provider-scvmm-new
    app.kubernetes.io/managed-by: kustomize
  name: scvmmnamepool-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - scvmmnamepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - scvmmnamepools/status
  verbs:
  - get
