apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scvmmmachines.infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/provider: infrastructure-scvmm
    cluster.x-k8s.io/v1alpha3: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/lifecycle: shared
