apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ScvmmProvider
metadata:
  labels:
    app.kubernetes.io/name: scvmmprovider
    app.kubernetes.io/instance: scvmmprovider-sample
    app.kubernetes.io/part-of: cluster-api-provider-scvmm-new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-scvmm-new
  name: scvmmprovider-sample
spec:
  # TODO(user): Add fields here
