name: Docker Image Release

on:
  push:
    tags: [ 'v*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner}}/cluster-api-provider-scvmm:${GITHUB_REF_NAME}
      env:
        DOCKER_BUILDKIT: "1"
    - name: Push the image to ghcr
      run: docker push ghcr.io/${{ github.repository_owner}}/cluster-api-provider-scvmm:${GITHUB_REF_NAME}
