name: Manifest Release

on:
  push:
    tags: [ 'v*', '!v*-rc*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build manifests
      run: make release
    - name: Upload manifest
      uses: softprops/action-gh-release@v1
      with:
        files: |
          out/metadata.yaml
          out/infrastructure-components.yaml
